/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.proyecto.vistas;

import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author pinvalda
 */
public class VistaJuego3 extends javax.swing.JFrame {

    /**
     * Creates new form vistaJuego3
     */
    public VistaJuego3() {

        initComponents();

    }

    public JToggleButton getBotonFalso() {
        return BotonFalso;
    }

    public void setBotonFalso(JToggleButton BotonFalso) {
        this.BotonFalso = BotonFalso;
    }

    public JToggleButton getBotonVerdadero() {
        return BotonVerdadero;
    }

    public void setBotonVerdadero(JToggleButton BotonVerdadero) {
        this.BotonVerdadero = BotonVerdadero;
    }

    public JLabel getEtiquetaImagen() {
        return EtiquetaImagen;
    }

    public void setEtiquetaImagen(JLabel EtiquetaImagen) {
        this.EtiquetaImagen = EtiquetaImagen;
    }

    public JLabel getEtiquetaNumeroRespuestasCorrectas() {
        return EtiquetaNumeroRespuestasCorrectas;
    }

    public void setEtiquetaNumeroRespuestasCorrectas(JLabel EtiquetaNumeroRespuestasCorrectas) {
        this.EtiquetaNumeroRespuestasCorrectas = EtiquetaNumeroRespuestasCorrectas;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelTitulo = new javax.swing.JPanel();
        EtiquetaTituloJuego3 = new javax.swing.JLabel();
        PanelImagenes = new javax.swing.JPanel();
        EtiquetaJuego3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaImagen = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        EtiquetaRespuestasCorrectas = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        EtiquetaNumeroRespuestasCorrectas = new javax.swing.JLabel();
        BotonVerdadero = new javax.swing.JToggleButton();
        BotonFalso = new javax.swing.JToggleButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(177, 0), new java.awt.Dimension(177, 0), new java.awt.Dimension(200, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTitulo.setPreferredSize(new java.awt.Dimension(610, 50));

        EtiquetaTituloJuego3.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        EtiquetaTituloJuego3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTituloJuego3.setText("Juego 3: Gregorio Fernández");
        EtiquetaTituloJuego3.setPreferredSize(new java.awt.Dimension(600, 50));
        PanelTitulo.add(EtiquetaTituloJuego3);

        getContentPane().add(PanelTitulo, java.awt.BorderLayout.PAGE_START);

        PanelImagenes.setMinimumSize(new java.awt.Dimension(200, 200));
        PanelImagenes.setPreferredSize(new java.awt.Dimension(200, 300));
        PanelImagenes.setLayout(new java.awt.BorderLayout());

        EtiquetaJuego3.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaJuego3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego3.setText("Selecciona si que crees que es de Gregorio Fernández");
        EtiquetaJuego3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego3.setPreferredSize(new java.awt.Dimension(200, 50));
        PanelImagenes.add(EtiquetaJuego3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        EtiquetaImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen.setMinimumSize(new java.awt.Dimension(200, 200));
        EtiquetaImagen.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.add(EtiquetaImagen, java.awt.BorderLayout.CENTER);
        EtiquetaImagen.getAccessibleContext().setAccessibleDescription("");

        PanelImagenes.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelImagenes, java.awt.BorderLayout.CENTER);

        PanelBotones.setMinimumSize(new java.awt.Dimension(97, 80));
        PanelBotones.setPreferredSize(new java.awt.Dimension(215, 80));

        EtiquetaRespuestasCorrectas.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        EtiquetaRespuestasCorrectas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EtiquetaRespuestasCorrectas.setText("Respuestas Correctas ");
        PanelBotones.add(EtiquetaRespuestasCorrectas);
        PanelBotones.add(filler1);
        PanelBotones.add(EtiquetaNumeroRespuestasCorrectas);

        BotonVerdadero.setBackground(new java.awt.Color(51, 255, 0));
        buttonGroup1.add(BotonVerdadero);
        BotonVerdadero.setText("VERDADERO");
        BotonVerdadero.setPreferredSize(new java.awt.Dimension(200, 60));
        PanelBotones.add(BotonVerdadero);

        BotonFalso.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(BotonFalso);
        BotonFalso.setText("FALSO");
        BotonFalso.setPreferredSize(new java.awt.Dimension(200, 60));
        PanelBotones.add(BotonFalso);
        PanelBotones.add(filler2);

        getContentPane().add(PanelBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaJuego3().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonFalso;
    private javax.swing.JToggleButton BotonVerdadero;
    private javax.swing.JLabel EtiquetaImagen;
    private javax.swing.JLabel EtiquetaJuego3;
    private javax.swing.JLabel EtiquetaNumeroRespuestasCorrectas;
    private javax.swing.JLabel EtiquetaRespuestasCorrectas;
    private javax.swing.JLabel EtiquetaTituloJuego3;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelImagenes;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
