/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.proyecto.vistas;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author pinvalda
 */


public class VistaJuego4 extends javax.swing.JFrame {

    public JLabel getEtiquetaImagen1() {
        return EtiquetaImagen1;
    }

    public void setEtiquetaImagen1(JLabel EtiquetaImagen1) {
        this.EtiquetaImagen1 = EtiquetaImagen1;
    }

    public JLabel getEtiquetaImagen2() {
        return EtiquetaImagen2;
    }

    public void setEtiquetaImagen2(JLabel EtiquetaImagen2) {
        this.EtiquetaImagen2 = EtiquetaImagen2;
    }

    public JLabel getEtiquetaImagen3() {
        return EtiquetaImagen3;
    }

    public void setEtiquetaImagen3(JLabel EtiquetaImagen3) {
        this.EtiquetaImagen3 = EtiquetaImagen3;
    }

    public JLabel getEtiquetaImagen4() {
        return EtiquetaImagen4;
    }

    public void setEtiquetaImagen4(JLabel EtiquetaImagen4) {
        this.EtiquetaImagen4 = EtiquetaImagen4;
    }

    public JLabel getEtiquetaImagen5() {
        return EtiquetaImagen5;
    }

    public void setEtiquetaImagen5(JLabel EtiquetaImagen5) {
        this.EtiquetaImagen5 = EtiquetaImagen5;
    }

    public JLabel getEtiquetaImagen6() {
        return EtiquetaImagen6;
    }

    public void setEtiquetaImagen6(JLabel EtiquetaImagen6) {
        this.EtiquetaImagen6 = EtiquetaImagen6;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public void setjPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    /**
     * Creates new form vistaJuego4
     */
    public VistaJuego4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        EtiquetaImagen1 = new javax.swing.JLabel();
        EtiquetaImagen2 = new javax.swing.JLabel();
        EtiquetaImagen3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaImagen4 = new javax.swing.JLabel();
        EtiquetaImagen5 = new javax.swing.JLabel();
        EtiquetaImagen6 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(filler1, java.awt.BorderLayout.PAGE_START);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Juego 4: Coloca en el mapa");
        jLabel3.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel5.setLayout(new java.awt.GridLayout(3, 0, 0, 14));

        EtiquetaImagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "1) Primavera", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("NSimSun", 0, 13))); // NOI18N
        EtiquetaImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EtiquetaImagen1MouseClicked(evt);
            }
        });
        jPanel5.add(EtiquetaImagen1);

        EtiquetaImagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "2) El hijo del hombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("NSimSun", 0, 13))); // NOI18N
        jPanel5.add(EtiquetaImagen2);

        EtiquetaImagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "3) El beso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("NSimSun", 0, 13))); // NOI18N
        EtiquetaImagen3.setMaximumSize(new java.awt.Dimension(200, 200));
        EtiquetaImagen3.setMinimumSize(new java.awt.Dimension(200, 200));
        EtiquetaImagen3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel5.add(EtiquetaImagen3);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 300));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 0, 20));

        EtiquetaImagen4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "4) El caminante sobre el mar de nubes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("NSimSun", 0, 13))); // NOI18N
        jPanel1.add(EtiquetaImagen4);

        EtiquetaImagen5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "5) El angel herido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("NSimSun", 0, 13))); // NOI18N
        jPanel1.add(EtiquetaImagen5);

        EtiquetaImagen6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true), "6) El fusilamiento del 3 de Mayo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("NSimSun", 0, 13))); // NOI18N
        jPanel1.add(EtiquetaImagen6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);
        getContentPane().add(filler2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EtiquetaImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtiquetaImagen1MouseClicked

    }//GEN-LAST:event_EtiquetaImagen1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
////        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(VistaJuego4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(VistaJuego4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(VistaJuego4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(VistaJuego4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaJuego4().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaImagen1;
    private javax.swing.JLabel EtiquetaImagen2;
    private javax.swing.JLabel EtiquetaImagen3;
    private javax.swing.JLabel EtiquetaImagen4;
    private javax.swing.JLabel EtiquetaImagen5;
    private javax.swing.JLabel EtiquetaImagen6;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
