/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.proyecto.vistas;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author pinvalda
 */
public class VistaJuego1 extends javax.swing.JFrame {
    
    /**
     * Creates new form vistaJuego1
     */
    public VistaJuego1() {
        initComponents();

    }

    public JButton getBotonSiguienteFin() {
        return BotonSiguienteFin;
    }

    public void setBotonSiguienteFin(JButton BotonSiguienteFin) {
        this.BotonSiguienteFin = BotonSiguienteFin;
    }

    public JLabel getEtiquetaFotos() {
        return EtiquetaFotos;
    }

    public void setEtiquetaFotos(JLabel EtiquetaFotos) {
        this.EtiquetaFotos = EtiquetaFotos;
    }

    public JComboBox<String> getjComboBoxOpciones() {
        return jComboBoxOpciones;
    }

    public void setjComboBoxOpciones(JComboBox<String> jComboBoxOpciones) {
        this.jComboBoxOpciones = jComboBoxOpciones;
    }

    public JLabel getEtiquetaNumeroRespuestasCorrectas() {
        return EtiquetaNumeroRespuestasCorrectas;
    }

    public void setEtiquetaNumeroRespuestasCorrectas(JLabel EtiquetaNumeroRespuestasCorrectas) {
        this.EtiquetaNumeroRespuestasCorrectas = EtiquetaNumeroRespuestasCorrectas;
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        EtiquetaTituloJuego1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaJuego1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        EtiquetaRespuestasCorrectas = new javax.swing.JLabel();
        EtiquetaNumeroRespuestasCorrectas = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jComboBoxOpciones = new javax.swing.JComboBox<>();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(80, 32767));
        BotonSiguienteFin = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        EtiquetaFotos = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EtiquetaTituloJuego1.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        EtiquetaTituloJuego1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTituloJuego1.setText("Juego 1: ¿Quién Lo Hizo?");
        EtiquetaTituloJuego1.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel2.add(EtiquetaTituloJuego1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        EtiquetaJuego1.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaJuego1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego1.setText("Indica el autor y el nombre de la obra");
        EtiquetaJuego1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(EtiquetaJuego1, java.awt.BorderLayout.NORTH);

        EtiquetaRespuestasCorrectas.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        EtiquetaRespuestasCorrectas.setText("Respuestas Correctas ");
        jPanel3.add(EtiquetaRespuestasCorrectas);
        jPanel3.add(EtiquetaNumeroRespuestasCorrectas);
        jPanel3.add(filler5);

        jComboBoxOpciones.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel3.add(jComboBoxOpciones);
        jPanel3.add(filler4);
        jPanel3.add(filler3);

        BotonSiguienteFin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonSiguienteFin.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel3.add(BotonSiguienteFin);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        EtiquetaFotos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaFotos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaFotos.setPreferredSize(new java.awt.Dimension(901, 297));
        jPanel5.add(EtiquetaFotos, java.awt.BorderLayout.CENTER);
        jPanel5.add(filler1, java.awt.BorderLayout.LINE_START);
        jPanel5.add(filler2, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaJuego1().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSiguienteFin;
    private javax.swing.JLabel EtiquetaFotos;
    private javax.swing.JLabel EtiquetaJuego1;
    private javax.swing.JLabel EtiquetaNumeroRespuestasCorrectas;
    private javax.swing.JLabel EtiquetaRespuestasCorrectas;
    private javax.swing.JLabel EtiquetaTituloJuego1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JComboBox<String> jComboBoxOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
