/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.proyecto.vistas;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Pint0
 */
public class VistaRankings extends javax.swing.JFrame {

    public JButton getBotonBuscarJugador() {
        return BotonBuscarJugador;

    }

    public void setBotonBuscarJugador(JButton BotonBuscarJugador) {
        this.BotonBuscarJugador = BotonBuscarJugador;
    }

    public JTable getTablaRanking() {
        return TablaRanking;
    }

    public void setTablaRanking(JTable TablaRanking) {
        this.TablaRanking = TablaRanking;
    }

    public VistaRankings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanelCabecera = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        EtiquetaRanking = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        BotonBuscarJugador = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRanking = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setLayout(new java.awt.BorderLayout());
        PanelContenedor.add(filler4, java.awt.BorderLayout.PAGE_START);

        jPanelCabecera.setLayout(new java.awt.GridLayout(1, 0, 20, 0));
        jPanelCabecera.add(filler1);

        EtiquetaRanking.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        EtiquetaRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaRanking.setText("Ranking");
        EtiquetaRanking.setMaximumSize(new java.awt.Dimension(118, 40));
        EtiquetaRanking.setPreferredSize(new java.awt.Dimension(38, 40));
        jPanelCabecera.add(EtiquetaRanking);
        jPanelCabecera.add(filler3);

        BotonBuscarJugador.setText("Buscar Jugador");
        jPanelCabecera.add(BotonBuscarJugador);

        PanelContenedor.add(jPanelCabecera, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        TablaRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaRanking.setColumnSelectionAllowed(false);
        TablaRanking.setEnabled(false);
        jScrollPane1.setViewportView(TablaRanking);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel5.add(filler2, java.awt.BorderLayout.PAGE_START);

        PanelContenedor.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaRankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaRankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaRankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaRankings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaRankings().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarJugador;
    private javax.swing.JLabel EtiquetaRanking;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JTable TablaRanking;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
