/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.proyecto.vistas;

import javax.swing.JLabel;
import javax.swing.JToggleButton;


/**
 *
 * @author pinvalda
 */
public class VistaJuego2 extends javax.swing.JFrame  {
    /**
     * Creates new form vistaJuego2
     */
    public VistaJuego2() {
        initComponents();
   }

    public JToggleButton getBotonFalso() {
        return BotonFalso;
    }

    public void setBotonFalso(JToggleButton BotonFalso) {
        this.BotonFalso = BotonFalso;
    }

    public JToggleButton getBotonVerdadero() {
        return BotonVerdadero;
    }

    public void setBotonVerdadero(JToggleButton BotonVerdadero) {
        this.BotonVerdadero = BotonVerdadero;
    }

    public JLabel getEtiquetaImagen() {
        return EtiquetaImagen;
    }

    public void setEtiquetaImagen(JLabel EtiquetaImagen) {
        this.EtiquetaImagen = EtiquetaImagen;
    }

    public JLabel getEtiquetaMuseo() {
        return EtiquetaMuseo;
    }

    public void setEtiquetaMuseo(JLabel EtiquetaMuseo) {
        this.EtiquetaMuseo = EtiquetaMuseo;
    }

    public JLabel getEtiquetaNumeroRespuestasCorrectas() {
        return EtiquetaNumeroRespuestasCorrectas;
    }

    public void setEtiquetaNumeroRespuestasCorrectas(JLabel EtiquetaNumeroRespuestasCorrectas) {
        this.EtiquetaNumeroRespuestasCorrectas = EtiquetaNumeroRespuestasCorrectas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoVerdaderoFalso = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        EtiquetaTituloJuego2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaMuseo = new javax.swing.JLabel();
        EtiquetaImagen = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(200, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(150, 0), new java.awt.Dimension(200, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 10));
        jPanel3 = new javax.swing.JPanel();
        EtiquetaRespuestasCorrectas = new javax.swing.JLabel();
        EtiquetaNumeroRespuestasCorrectas = new javax.swing.JLabel();
        BotonVerdadero = new javax.swing.JToggleButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        BotonFalso = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EtiquetaTituloJuego2.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        EtiquetaTituloJuego2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTituloJuego2.setText("Juego 2: ¿Verdadero o Falso?");
        EtiquetaTituloJuego2.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel2.add(EtiquetaTituloJuego2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        EtiquetaMuseo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaMuseo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaMuseo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaMuseo.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(EtiquetaMuseo, java.awt.BorderLayout.NORTH);

        EtiquetaImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaImagen.setPreferredSize(new java.awt.Dimension(600, 190));
        jPanel1.add(EtiquetaImagen, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler2, java.awt.BorderLayout.LINE_START);
        jPanel1.add(filler3, java.awt.BorderLayout.LINE_END);
        jPanel1.add(filler5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        EtiquetaRespuestasCorrectas.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        EtiquetaRespuestasCorrectas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EtiquetaRespuestasCorrectas.setText("Respuestas Correctas ");
        jPanel3.add(EtiquetaRespuestasCorrectas);
        jPanel3.add(EtiquetaNumeroRespuestasCorrectas);

        BotonVerdadero.setBackground(new java.awt.Color(0, 255, 0));
        GrupoVerdaderoFalso.add(BotonVerdadero);
        BotonVerdadero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonVerdadero.setText("VERDADERO");
        BotonVerdadero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonVerdadero.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel3.add(BotonVerdadero);
        jPanel3.add(filler4);

        BotonFalso.setBackground(new java.awt.Color(255, 0, 0));
        GrupoVerdaderoFalso.add(BotonFalso);
        BotonFalso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonFalso.setText("FALSO");
        BotonFalso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonFalso.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel3.add(BotonFalso);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaJuego2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaJuego2().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonFalso;
    private javax.swing.JToggleButton BotonVerdadero;
    private javax.swing.JLabel EtiquetaImagen;
    private javax.swing.JLabel EtiquetaMuseo;
    private javax.swing.JLabel EtiquetaNumeroRespuestasCorrectas;
    private javax.swing.JLabel EtiquetaRespuestasCorrectas;
    private javax.swing.JLabel EtiquetaTituloJuego2;
    private javax.swing.ButtonGroup GrupoVerdaderoFalso;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}


