/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.proyecto.vistas;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;


/**
 *
 * @author Lucia
 */
public class VistaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form TEMAGUI
     */
    public VistaPrincipal() {
        initComponents();
    }

    public JToggleButton getBotonCambiarTema() {
        return BotonCambiarTema;
    }

    public void setBotonCambiarTema(JToggleButton BotonCambiarTema) {
        this.BotonCambiarTema = BotonCambiarTema;
    }

    public JButton getBotonJuego1() {
        return BotonJuego1;
    }

    public void setBotonJuego1(JButton BotonJuego1) {
        this.BotonJuego1 = BotonJuego1;
    }

    public JButton getBotonJuego2() {
        return BotonJuego2;
    }

    public void setBotonJuego2(JButton BotonJuego2) {
        this.BotonJuego2 = BotonJuego2;
    }

    public JButton getBotonJuego3() {
        return BotonJuego3;
    }

    public void setBotonJuego3(JButton BotonJuego3) {
        this.BotonJuego3 = BotonJuego3;
    }

    public JButton getBotonJuego4() {
        return BotonJuego4;
    }

    public void setBotonJuego4(JButton BotonJuego4) {
        this.BotonJuego4 = BotonJuego4;
    }

    public JButton getBotonRanking() {
        return BotonRanking;
    }

    public void setBotonRanking(JButton BotonRanking) {
        this.BotonRanking = BotonRanking;
    }

    public JLabel getEtiquetaImagenJuego1() {
        return EtiquetaImagenJuego1;
    }

    public void setEtiquetaImagenJuego1(JLabel EtiquetaImagenJuego1) {
        this.EtiquetaImagenJuego1 = EtiquetaImagenJuego1;
    }

    public JLabel getEtiquetaImagenJuego2() {
        return EtiquetaImagenJuego2;
    }

    public void setEtiquetaImagenJuego2(JLabel EtiquetaImagenJuego2) {
        this.EtiquetaImagenJuego2 = EtiquetaImagenJuego2;
    }

    public JLabel getEtiquetaImagenJuego3() {
        return EtiquetaImagenJuego3;
    }

    public void setEtiquetaImagenJuego3(JLabel EtiquetaImagenJuego3) {
        this.EtiquetaImagenJuego3 = EtiquetaImagenJuego3;
    }

    public JLabel getEtiquetaImagenJuego4() {
        return EtiquetaImagenJuego4;
    }

    public void setEtiquetaImagenJuego4(JLabel EtiquetaImagenJuego4) {
        this.EtiquetaImagenJuego4 = EtiquetaImagenJuego4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        Cabecera = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(400, 0), new java.awt.Dimension(400, 32767));
        EtiquetaTituloDIM = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(600, 0), new java.awt.Dimension(600, 32767));
        BotonCambiarTema = new javax.swing.JToggleButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 32767));
        PanelCentral = new javax.swing.JPanel();
        PanelJuego1 = new javax.swing.JPanel();
        EtiquetaJuego1 = new javax.swing.JLabel();
        BotonJuego1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        EtiquetaImagenJuego1 = new javax.swing.JLabel();
        PanelJuego2 = new javax.swing.JPanel();
        BotonJuego2 = new javax.swing.JButton();
        EtiquetaJuego2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        EtiquetaImagenJuego2 = new javax.swing.JLabel();
        PanelJuego3 = new javax.swing.JPanel();
        BotonJuego3 = new javax.swing.JButton();
        EtiquetaJuego3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EtiquetaImagenJuego3 = new javax.swing.JLabel();
        PanelJuego4 = new javax.swing.JPanel();
        BotonJuego4 = new javax.swing.JButton();
        EtiquetaJuego4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaImagenJuego4 = new javax.swing.JLabel();
        PanelFinal = new javax.swing.JPanel();
        BotonRanking = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(280, 40), new java.awt.Dimension(32767, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(280, 40), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelContenedor.setLayout(new java.awt.BorderLayout());

        Cabecera.setMinimumSize(new java.awt.Dimension(957, 90));
        Cabecera.setPreferredSize(new java.awt.Dimension(1630, 90));
        Cabecera.setLayout(new javax.swing.BoxLayout(Cabecera, javax.swing.BoxLayout.LINE_AXIS));
        Cabecera.add(filler5);

        EtiquetaTituloDIM.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        EtiquetaTituloDIM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTituloDIM.setText("Día Internacional de los Museos");
        EtiquetaTituloDIM.setToolTipText("");
        EtiquetaTituloDIM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaTituloDIM.setPreferredSize(new java.awt.Dimension(600, 50));
        Cabecera.add(EtiquetaTituloDIM);
        Cabecera.add(filler8);

        BotonCambiarTema.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonCambiarTema.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Cabecera.add(BotonCambiarTema);
        Cabecera.add(filler7);

        PanelContenedor.add(Cabecera, java.awt.BorderLayout.NORTH);

        PanelCentral.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        PanelJuego1.setLayout(new java.awt.BorderLayout());

        EtiquetaJuego1.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaJuego1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego1.setText("¿Quién lo hizo?");
        EtiquetaJuego1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego1.setPreferredSize(new java.awt.Dimension(103, 40));
        PanelJuego1.add(EtiquetaJuego1, java.awt.BorderLayout.NORTH);

        BotonJuego1.setText("Juego 1");
        BotonJuego1.setPreferredSize(new java.awt.Dimension(70, 40));
        PanelJuego1.add(BotonJuego1, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        EtiquetaImagenJuego1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagenJuego1.setPreferredSize(new java.awt.Dimension(180, 260));
        jPanel4.add(EtiquetaImagenJuego1, java.awt.BorderLayout.CENTER);

        PanelJuego1.add(jPanel4, java.awt.BorderLayout.CENTER);

        PanelCentral.add(PanelJuego1);

        PanelJuego2.setLayout(new java.awt.BorderLayout());

        BotonJuego2.setText("Juego 2");
        BotonJuego2.setPreferredSize(new java.awt.Dimension(70, 40));
        PanelJuego2.add(BotonJuego2, java.awt.BorderLayout.SOUTH);

        EtiquetaJuego2.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaJuego2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego2.setText("¿Verdadero o Falso?");
        EtiquetaJuego2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego2.setPreferredSize(new java.awt.Dimension(135, 40));
        PanelJuego2.add(EtiquetaJuego2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        EtiquetaImagenJuego2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagenJuego2.setPreferredSize(new java.awt.Dimension(180, 260));
        jPanel3.add(EtiquetaImagenJuego2, java.awt.BorderLayout.CENTER);

        PanelJuego2.add(jPanel3, java.awt.BorderLayout.CENTER);

        PanelCentral.add(PanelJuego2);

        PanelJuego3.setLayout(new java.awt.BorderLayout());

        BotonJuego3.setText("Juego 3");
        BotonJuego3.setPreferredSize(new java.awt.Dimension(70, 40));
        PanelJuego3.add(BotonJuego3, java.awt.BorderLayout.SOUTH);

        EtiquetaJuego3.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaJuego3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego3.setText("Gregorio Fernández");
        EtiquetaJuego3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego3.setPreferredSize(new java.awt.Dimension(134, 40));
        PanelJuego3.add(EtiquetaJuego3, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        EtiquetaImagenJuego3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagenJuego3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaImagenJuego3.setPreferredSize(new java.awt.Dimension(180, 260));
        jPanel2.add(EtiquetaImagenJuego3, java.awt.BorderLayout.CENTER);

        PanelJuego3.add(jPanel2, java.awt.BorderLayout.CENTER);

        PanelCentral.add(PanelJuego3);

        PanelJuego4.setLayout(new java.awt.BorderLayout());

        BotonJuego4.setText("Juego 4");
        BotonJuego4.setPreferredSize(new java.awt.Dimension(70, 40));
        PanelJuego4.add(BotonJuego4, java.awt.BorderLayout.SOUTH);

        EtiquetaJuego4.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        EtiquetaJuego4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego4.setText("Coloca en el mapa");
        EtiquetaJuego4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EtiquetaJuego4.setPreferredSize(new java.awt.Dimension(124, 40));
        PanelJuego4.add(EtiquetaJuego4, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        EtiquetaImagenJuego4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaImagenJuego4.setPreferredSize(new java.awt.Dimension(180, 260));
        jPanel1.add(EtiquetaImagenJuego4, java.awt.BorderLayout.CENTER);

        PanelJuego4.add(jPanel1, java.awt.BorderLayout.CENTER);

        PanelCentral.add(PanelJuego4);

        PanelContenedor.add(PanelCentral, java.awt.BorderLayout.CENTER);

        PanelFinal.setLayout(new java.awt.BorderLayout());
        PanelFinal.add(BotonRanking, java.awt.BorderLayout.CENTER);
        PanelFinal.add(filler1, java.awt.BorderLayout.PAGE_START);
        PanelFinal.add(filler2, java.awt.BorderLayout.PAGE_END);
        PanelFinal.add(filler3, java.awt.BorderLayout.LINE_START);
        PanelFinal.add(filler4, java.awt.BorderLayout.LINE_END);

        PanelContenedor.add(PanelFinal, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonCambiarTema;
    private javax.swing.JButton BotonJuego1;
    private javax.swing.JButton BotonJuego2;
    private javax.swing.JButton BotonJuego3;
    private javax.swing.JButton BotonJuego4;
    private javax.swing.JButton BotonRanking;
    private javax.swing.JPanel Cabecera;
    private javax.swing.JLabel EtiquetaImagenJuego1;
    private javax.swing.JLabel EtiquetaImagenJuego2;
    private javax.swing.JLabel EtiquetaImagenJuego3;
    private javax.swing.JLabel EtiquetaImagenJuego4;
    private javax.swing.JLabel EtiquetaJuego1;
    private javax.swing.JLabel EtiquetaJuego2;
    private javax.swing.JLabel EtiquetaJuego3;
    private javax.swing.JLabel EtiquetaJuego4;
    private javax.swing.JLabel EtiquetaTituloDIM;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelFinal;
    private javax.swing.JPanel PanelJuego1;
    private javax.swing.JPanel PanelJuego2;
    private javax.swing.JPanel PanelJuego3;
    private javax.swing.JPanel PanelJuego4;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
